# Generated by Django 4.2.16 on 2024-09-28 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
