# Generated by Django 4.2.16 on 2024-09-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
